apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gpu-parrot-paraphraser.fullname" . }}
  labels:
    {{- include "gpu-parrot-paraphraser.labels" . | nindent 4 }}
type: Opaque
data:
  aws-access-key-id: {{ required "awsDynamodbAllActions.awsAccessKeyId is required"
    .Values.awsDynamodbAllActions.awsAccessKeyId | b64enc | quote }}
  aws-secret-access-key: {{ required "awsDynamodbAllActions.awsSecretAccessKey is required" .Values.awsDynamodbAllActions.awsSecretAccessKey | b64enc | quote }}
type: Opaque