apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gpu-parrot-paraphraser.fullname" . }}
  labels:
    {{- include "gpu-parrot-paraphraser.labels" . | nindent 4 }}
type: Opaque
data:
  aws_access_key_id: {{ required "awsDynamodbAllActions.awsAccessKeyId is required"
    .Values.awsDynamodbAllActions.awsAccessKeyId | b64enc | quote }}
  aws_secret_access_key: {{ required "awsDynamodbAllActions.awsSecretAccessKey is required" .Values.awsDynamodbAllActions.awsSecretAccessKey | b64enc | quote }}
  credentials: {{ required "awsDynamodbAllActions.credentials is required" .Values.awsDynamodbAllActions.credentials
    | b64enc | quote }}
type: Opaque